import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // Changed Geist to Inter, Geist_Mono to Roboto_Mono
import "./globals.css";

const inter = Inter({ // Changed geistSans to inter
  variable: "--font-geist-sans", // Keeping variable name for CSS compatibility, but font is Inter
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({ // Changed geistMono to robotoMono
  variable: "--font-geist-mono", // Keeping variable name for CSS compatibility, but font is Roboto_Mono
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`} // Updated to use inter and robotoMono variables
      >
        {children}
      </body>
    </html>
  );
}
